name: Build Image
on: [pull_request]
jobs:
  build-image-without-pushing:
    runs-on: ubuntu-latest
    steps:  
    - name: Checkout PR
      uses: actions/checkout@v2
      
    - name: Test Build
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: 'true'
        IMAGE_NAME: "scottyhq/github-action"

    - name: Report Image Size and Conda Packages
      run: |
        docker images
        docker run ${DOCKER_ORG}/${{ matrix.IMAGE }}:PR conda list --export
